[package]
name = "raytracer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
raytracer-lib = { path = "../raytracer-lib" }
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17.8"
image = "0.24"
