[package]
name = "raytracer-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
raytracer-lib = { path = "../raytracer-lib" }
wasm-bindgen = "0.2.95"
serde_json = "1.0.132"
serde = { version = "1.0.215", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["rlib", "cdylib"]  # To enable usage as a library in WASM
