[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--max-memory=4294967296",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--shared-memory"
]

[unstable]
build-std = ["panic_abort", "std"]
